### ISSUE TITLE
Lost features

### ISSUE THREAD

**Issue by InnocentusLime** [rustgd/cgmath#501]
There are some fancy methods implemented for `Decomposed<V : VectorSpace, R>`, when `V : EuclideanSpace`. However that trait bound introduces a problem:
There is no type `T` which satisfies both `EuclideanSpace` and `VectorSpace` (`EuclideanSpace` is only implemented for `Point`s, but they do not implement `VectorSpace`). As a result `Decomposed<V : VectorSpace, R> where V : EuclideanSpace` is an uninhabited type.

**Comment by nstoddard** [comment]
Can you give a specific example of a method that isn't callable for any type? I don't see any methods that require both `EuclideanSpace` and `VectorSpace`, but maybe I missed some. The closest I can find is an impl that requires `P: EuclideanSpace` and `P::Diff: VectorSpace`, but `Point3` etc would satisfy that (since `Point3::Diff` would be `Vector3`).

**Comment by InnocentusLime** [comment]
Okay, you are right. I got lost in the trait bounds. xD
